/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedBulletinRouteImport } from './routes/_authenticated/bulletin'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedProductIdRouteImport } from './routes/_authenticated/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulletinRoute = AuthenticatedBulletinRouteImport.update({
  id: '/bulletin',
  path: '/bulletin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductIdRoute = AuthenticatedProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/bulletin': typeof AuthenticatedBulletinRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/product/$id': typeof AuthenticatedProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/bulletin': typeof AuthenticatedBulletinRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/product/$id': typeof AuthenticatedProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/bulletin': typeof AuthenticatedBulletinRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/product/$id': typeof AuthenticatedProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/bulletin'
    | '/checkout'
    | '/home'
    | '/inbox'
    | '/notifications'
    | '/shop'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/bulletin'
    | '/checkout'
    | '/home'
    | '/inbox'
    | '/notifications'
    | '/shop'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/bulletin'
    | '/_authenticated/checkout'
    | '/_authenticated/home'
    | '/_authenticated/inbox'
    | '/_authenticated/notifications'
    | '/_authenticated/shop'
    | '/_authenticated/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulletin': {
      id: '/_authenticated/bulletin'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof AuthenticatedBulletinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product/$id': {
      id: '/_authenticated/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof AuthenticatedProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBulletinRoute: typeof AuthenticatedBulletinRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedProductIdRoute: typeof AuthenticatedProductIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBulletinRoute: AuthenticatedBulletinRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedProductIdRoute: AuthenticatedProductIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
